language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice unoconv tidy redis-server
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -v 1.7.0 -c travis.cfg
  - bin/buildout -N -t 12 -c travis.cfg
script: bin/test
